apiVersion: v2
name: reservation-service
description: Helm chart for PSS-nano Reservation Service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: base-service
    version: "1.0.0"
    repository: "file://../../base-service"
