apiVersion: v1
kind: ConfigMap
metadata:
  name: airline-ops-config
  namespace: airline-ops
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_GATEWAY_PORT: "3000"
  AUTH_SERVICE_PORT: "3001"
  RESERVATION_SERVICE_PORT: "3002"
  INVENTORY_SERVICE_PORT: "3003"
  PAYMENT_SERVICE_PORT: "3004"
  NOTIFICATION_SERVICE_PORT: "3005"
